### PR TITLE
Export numgrid as a CMake module

### PR DESCRIPTION
**Pull request by robertodr**
## Description
numgrid installation is now discoverable via a `find_package` command in CMake. To test this out:
- configure the project specifying a user-writable prefix
- `make install`
- in a scratch directory save this minimal `CMakeLists.txt`:
```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)

project(dummy CXX)

find_package(numgrid REQUIRED)
get_property(_loc TARGET numgrid::numgrid PROPERTY LOCATION)
message("Location of numgrid: ${_loc}")
```
- run the following commands:
```
mkdir -p build
cd build 
cmake .. -Dnumgrid_DIR=${prefix}/share/cmake/numgrid
```

## Other points covered by this PR
- [x] Use `M_PI` as defined in `cmath`, _i.e._ it's not hardcoded anymore
- [x] Use `std::` namespace to select C++ version of (some) math functions. 
   * **TODO** The error function is still taken from the C standard headers, I will submit a PR for moving the project to C++11 and modernize this point.
- [x] Update Autocmake and request CMake 3.0, at least.
- [x] Both dynamic and static libraries can be built now. `SHARED_LIBRARY_ONLY` and `STATIC_LIBRARY_ONLY` toggle the build of only one of the two options.
   * **TODO** When `STATIC_LIBRARY_ONLY` is selected, the Python interface will not work. How to deal with this case?
- [x] Dependencies of the project, _i.e._ the Lebedev-Laikov and Gtest code have been moved to subdirectories of `external/upstream`

### CODE REVIEW

**Comment by bast** [comment]
This will be very valuable - thanks a lot for doing this!

**Comment by robertodr** [comment]
Don't know why Travis is dying on this... I will investigate and I should be done with it by today. I will add other stuff in another PR, since this has become too big already. I can confirm that I can now do `make install` and then, in another `CMakeLists.txt` do `find_package(numgrid)` :smile_cat:

**Comment by robertodr** [comment]
@bast this is ready for review

**Comment by bast** [comment]
Thank you so much for the cleanup!

**Pull request merged**
